name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "bun"
      - run: curl -fsSL https://bun.sh/install | bash
      - run: bun install
      - run: bun lint && bun build
